### PR TITLE
Add support for EC2 IAM roles, via a config option 'token'

### PR DESCRIPTION
**Pull request by jeremyd2019**
which adds an x-amz-security-token header to requests.

### CODE REVIEW

**Comment by vsespb** [comment]
Hello. Thank you for this patch.

Are you sure it's 420 characters? I saw 240 in docs examples.
Can you clarify what tokens are allowed (in terms of Amazon documentation) - "session tokens"?
Don't you mind if I rename it to `session-token` or `iam-token`? `token` looks to short and general, and this feature is pretty rarely used (compared to what is used)

**Comment by vsespb** [comment]
p.s. I merged current version for now (to avoid problems with merge in the future) as it does not break existing behaviour..

**Comment by jeremyd2019** [comment]
My token was 420 characters.  I dug through the docs and all I could find about what the token is is "String".  Maybe it shouldn't have any validation on it?  I wasn't sure how to do that, though.

I hadn't read about "session tokens" until you had mentioned it.  I was using an IAM role on an EC2 instance.  Maybe the temporary access tokens through STS are smaller than the EC2 role tokens?

I don't mind if you rename it.  I'm kind of partial to security-token, since that matches the request header.

**Comment by vsespb** [comment]
Ok, I'll leave `token` then. Will change validation to allow any length from 20 to 1024 (as length is not documented). Will document it, and add some unit tests and release in new version.

**Comment by vsespb** [comment]
Ok, release in 0.957beta. Thanks again for the patch!

**Pull request merged**
