### PR TITLE
Ssl support

### PR DESCRIPTION
**Pull request by h110hawk**
Quick and dirty SSL support. I tested this out on my Mac. Hope you like it!

### CODE REVIEW

**Comment by vsespb** [comment]
Hi. Great work!

But I see several problems:
1. When I tested HTTPS like this, there was a problem that in HTTPS
   mode LWP::UserAgent handles network errors/signals different way.. i.e. whole script can crash if network go down (and if it does not crash sometimes, it does not mean it won't crash next time - it depends on what even happened on which stage of data transfer, also this can depend on lwp::useragent version). Well this can be easy fixed, I think, by surrounding request call with eval{}. But this should be tested..
2. I did not test how it handles fake HTTP certificate. It should protect user and stop working if certificate is wrong and
   connection is a fake. Well seems this is the case.
3. I usually do unit tests for config options, but there is some mess now in "t/" directory, so I'll do it by myself.
4. Seems I use tabs, you use spaces.
5. Big problem, that actually there are two branches: "master" and "development". Master only contain stable, release version,
   fixes to docs can go there directly, but fixes to code should go to "development". Also I made changes to ConfigEngine in "development" recently,
   which conflict with your code.

Well, I think 1-4 is not a big problem.

but (5). hm.

you could try on your side:

```
git checkout development
git merge ssl-support
git push
```

and make another pull request which go from "development" to "development" branches.

but I think on `git merge ssl-support` stage there will be conflicts. If you don't have experience merging conflicts in git and don't wish
to try, there can be another way:

a) make new fresh checkout of repo:

```
https://github.com/vsespb/mt-aws-glacier.git
git checkout development
```

b) just file copy your versions of GlacierRequest.pm, README.md and mtglacier.pl to this new location

c) ConfigEngine.pm - manually insert that "protocol" section

d) check that it looks ok, and make a commit.

e) forget about master branch, use only development.

p.s.
difference between master and development can be viewed as https://github.com/vsespb/mt-aws-glacier/compare/master...development

**Comment by vsespb** [comment]
I replaced in my last comment `git merge master` with `git merge ssl-support`

**Comment by vsespb** [comment]
Another thing to do is check which additional modules required for SSL support. I think (at least) on Ubuntu there are some. I will check on fresh Ubuntu and CentOs.

**Comment by h110hawk** [comment]
Ok, I believe I've merged it all together. I'll try to use tabs instead of spaces, at work we use spaces so I get in the habit. I'm (obviously?) not a developer by trade, I know just enough to frustrate them. 
1. This is untested.
2. LWP handles cert validation against your chosen CA file - defaulting to Mozilla::CA. I disable validation for use on local debugging, but leave it on for remote connections. I tested this using openssl s_server and a cert with a valid CA signature but CN mismatch - script yields a 500 error. With validation disabled it connects and makes the request fine.
3. Unit tests are something I've never written. Skimming the t/ directory I wasn't having much luck figuring out what I needed to do.

**Pull request closed without merging**
