### PR TITLE
Some repo cosmetics

### PR DESCRIPTION
**Pull request by GermanS**
add Build.PL and manifest
put packages into lib/ directory
put executables into bin/

### CODE REVIEW

**Comment by vsespb** [comment]
Hello. Thanks for your fixes!

One small problem: I have recently wrote an article about this script http://habrahabr.ru/post/150324/ . It does contain some instruction how to run it etc. So it contains "./mtglacier.pl ... " command.

Thus I would like to keep mtglacier.pl and cycletest.sh in the root directory until next (major) version. (btw cycletest.sh isn't working from bin directory now too).
Could you please move it back to root, i will merge your changes then.

**Comment by vsespb** [comment]
Also, what Glacier.pm for ?

**Comment by GermanS** [comment]
http://search.cpan.org/~leont/Module-Build-0.4003/lib/Module/Build/API.pod
pls, look at the section "script_files" 
"The default is to install any scripts found in a bin directory at the top level of the distribution"
so after the install the distribution parl Build.PL && make && make test && make install
mtglacier.pl will be  in directiory /usr/local/bin/ 

for example. you could review the contents of Template-Toolkit package
http://cpansearch.perl.org/src/ABW/Template-Toolkit-2.24/

Gracier.pm - it's just for versioning. You could rename it

**Comment by vsespb** [comment]
Ok, get it.
So, your fixes allow it to be deployed using Module::Build.
Unfortunately currently I cannot merge your changes.

Main reason is that I want keep it compatible with users who want just clone the repo and run the script, without installing ( see note above about article on habrahabr.ru ).

Yes, I am going to improve current packaging soon. And I will use Module::Build.

But there are things that blocks this task:
- Need to make some not a small internal code refactoring, including removing/adding modules.
- Yesterday someone published Net::Amazon::Glacier and Net::Amazon::Signature::V4. Need to wait to see if those modules fit my needs, and use it if they do, instead of my code.
  I really think of using Net::Amazon::Signature::V4. Not sure about Net::Amazon::Glacier - it's not ready yet and most likely won't work for mt-glacier well.
- Need rename modules. Maybe publish some on CPAN.
- Need to have production ready version.
- Need to have also Debian compatible packages.

After that I will prepage new directory structure, and do my best to make it compatible with your fork.

**Pull request closed without merging**
